# Generated by Django 3.2.13 on 2022-04-30 11:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80, verbose_name='作者')),
                ('content', ckeditor.fields.RichTextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('page_view', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('year', models.IntegerField(verbose_name='年份')),
            ],
            options={
                'verbose_name': '随笔日常记录',
                'db_table': 'db_dailLog',
                'ordering': ['-create_time'],
            },
        ),
    ]
