# Generated by Django 3.2.13 on 2022-05-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNum_cai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_num', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=32, verbose_name='IP地址')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '点踩数',
                'db_table': 'db_blog_cainum',
            },
        ),
        migrations.CreateModel(
            name='LikeNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_num', models.IntegerField(default=0)),
                ('like_cai', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=32, verbose_name='IP地址')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '点赞数',
                'db_table': 'db_blog_likenum',
            },
        ),
    ]
