# Generated by Django 3.2.13 on 2022-05-08 10:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='IP地址')),
                ('name', models.CharField(max_length=20, verbose_name='匿名')),
                ('content', ckeditor.fields.RichTextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ding', models.IntegerField(default=0, verbose_name='顶')),
                ('cai', models.IntegerField(default=0, verbose_name='踩')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='comment.reviewrecords')),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='comment.reviewrecords')),
            ],
            options={
                'verbose_name': '评论记录',
                'db_table': 'db_reviewrecords',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='G_reviewRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ip', models.CharField(max_length=32, verbose_name='IP地址')),
                ('name', models.CharField(max_length=20, verbose_name='匿名')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ding', models.IntegerField(default=0, verbose_name='顶')),
                ('cai', models.IntegerField(default=0, verbose_name='踩')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='comment.g_reviewrecords')),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='comment.g_reviewrecords')),
            ],
            options={
                'verbose_name': '通用_评论记录',
                'db_table': 'db_g_reviewrecords',
                'ordering': ['create_time'],
            },
        ),
    ]
